---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: k8s-flask
  template:
    metadata:
      labels:
        app: k8s-flask
    spec:
      containers:
        - name: k8s-flask-container
          image: estensen/k8s-flask
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-flask
spec:
  selector:
    app: k8s-flask
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 31234
  type: NodePort
